/**
 * AsteroidLearnMore.tsx
 *
 * Rich educational panel with three tabs:
 *   1. LEARN  — Long-form article generated by Gemini from NASA data
 *   2. QUIZ   — Interactive quiz to test understanding
 *   3. ASK    — Free-form input to ask anything about the asteroid
 */
import { useState, useCallback, useRef, useEffect } from 'react';
import { fetchAsteroidInfo } from '../../engine/asteroidInfoService';
import type { AsteroidChatInfo } from '../../engine/asteroidInfoService';
import {
  generateArticle,
  generateQuiz,
  askFreeQuestion,
  type ArticleSection,
  type QuizQuestion,
} from '../../engine/geminiService';

/* ── Props ─────────────────────────────────────────────────────── */

interface AsteroidLearnMoreProps {
  asteroidId: string;
  asteroidName: string;
  accent?: string;
  compact?: boolean;
}

type MainState = 'idle' | 'loading' | 'ready' | 'error';
type Tab = 'learn' | 'quiz' | 'ask';

/** A chat message in the Ask tab */
interface AskMsg {
  role: 'user' | 'bot';
  text: string;
}

/* ── Component ─────────────────────────────────────────────────── */

export default function AsteroidLearnMore({
  asteroidId,
  asteroidName,
  accent = '#4A90D9',
  compact = false,
}: AsteroidLearnMoreProps) {
  /* ── core state ── */
  const [mainState, setMainState] = useState<MainState>('idle');
  const [tab, setTab] = useState<Tab>('learn');
  const [errorMsg, setErrorMsg] = useState('');

  /* ── data ── */
  const [nasaInfo, setNasaInfo] = useState<AsteroidChatInfo | null>(null);
  const [article, setArticle] = useState<ArticleSection[]>([]);
  const [articleText, setArticleText] = useState(''); // plain text for context

  /* ── quiz state ── */
  const [quiz, setQuiz] = useState<QuizQuestion[]>([]);
  const [quizLoading, setQuizLoading] = useState(false);
  const [quizIdx, setQuizIdx] = useState(0);
  const [selected, setSelected] = useState<number | null>(null);
  const [score, setScore] = useState(0);
  const [answered, setAnswered] = useState(false);
  const [quizDone, setQuizDone] = useState(false);

  /* ── ask state ── */
  const [askMsgs, setAskMsgs] = useState<AskMsg[]>([]);
  const [askInput, setAskInput] = useState('');
  const [askLoading, setAskLoading] = useState(false);
  const askEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    askEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [askMsgs]);

  /* ── NASA context string for Gemini ── */
  const nasaContext = nasaInfo
    ? nasaInfo.qaList.map((q) => `${q.question}\n${q.answer}`).join('\n\n')
    : '';

  /* ── Open / close ── */
  const handleToggle = useCallback(async () => {
    if (mainState === 'ready') {
      setMainState('idle');
      return;
    }
    if (mainState === 'loading') return;

    setMainState('loading');
    setErrorMsg('');

    try {
      // 1. Fetch NASA data
      const info = await fetchAsteroidInfo(asteroidId, asteroidName);
      setNasaInfo(info);

      const ctx = info.qaList.map((q) => `${q.question}\n${q.answer}`).join('\n\n');

      // 2. Generate article with Gemini
      const sections = await generateArticle(asteroidName, ctx);
      setArticle(sections);

      const plainText = sections.map((s) => `${s.title}: ${s.content}`).join('\n\n');
      setArticleText(plainText);

      // Reset quiz / ask state
      setQuiz([]);
      setQuizIdx(0);
      setSelected(null);
      setScore(0);
      setAnswered(false);
      setQuizDone(false);
      setAskMsgs([]);
      setTab('learn');
      setMainState('ready');
    } catch (err: unknown) {
      let msg = 'Could not load — please try again.';
      if (err instanceof Error) {
        switch (err.message) {
          case 'MISSING_API_KEY':
            msg = 'Set VITE_GROQ_API_KEY in your .env file to enable this feature.';
            break;
          case 'RATE_LIMITED':
            msg = 'API rate limit hit — wait a moment and try again.';
            break;
          case 'API_KEY_INVALID':
            msg = 'API key is invalid or expired. Check your .env file.';
            break;
          case 'BAD_REQUEST':
            msg = 'Gemini rejected the request — try again.';
            break;
        }
      }
      console.error('AsteroidLearnMore error:', err);
      setErrorMsg(msg);
      setMainState('error');
    }
  }, [asteroidId, asteroidName, mainState]);

  /* ── Quiz: load on first visit ── */
  const handleQuizTab = useCallback(async () => {
    setTab('quiz');
    if (quiz.length > 0 || quizLoading) return;
    setQuizLoading(true);
    try {
      const qs = await generateQuiz(asteroidName, articleText);
      setQuiz(qs);
    } catch {
      setQuiz([]);
    } finally {
      setQuizLoading(false);
    }
  }, [asteroidName, articleText, quiz.length, quizLoading]);

  /* ── Quiz: select answer ── */
  const handleAnswer = (optIdx: number) => {
    if (answered) return;
    setSelected(optIdx);
    setAnswered(true);
    if (optIdx === quiz[quizIdx]?.correct) setScore((s) => s + 1);
  };

  const handleNext = () => {
    if (quizIdx + 1 >= quiz.length) {
      setQuizDone(true);
    } else {
      setQuizIdx((i) => i + 1);
      setSelected(null);
      setAnswered(false);
    }
  };

  const handleRetakeQuiz = () => {
    setQuizIdx(0);
    setSelected(null);
    setScore(0);
    setAnswered(false);
    setQuizDone(false);
  };

  /* ── Ask: send free-form question ── */
  const handleSend = useCallback(async () => {
    const q = askInput.trim();
    if (!q || askLoading) return;
    setAskInput('');
    setAskMsgs((prev) => [...prev, { role: 'user', text: q }]);
    setAskLoading(true);
    try {
      const answer = await askFreeQuestion(asteroidName, nasaContext, articleText, q);
      setAskMsgs((prev) => [...prev, { role: 'bot', text: answer }]);
    } catch {
      setAskMsgs((prev) => [
        ...prev,
        { role: 'bot', text: "Sorry, I couldn't reach the AI — try again in a moment!" },
      ]);
    } finally {
      setAskLoading(false);
    }
  }, [askInput, askLoading, asteroidName, nasaContext, articleText]);

  /* ── Tab config ── */
  const tabs: { key: Tab; label: string; icon: string }[] = [
    { key: 'learn', label: 'Learn', icon: '📖' },
    { key: 'quiz', label: 'Quiz', icon: '🧠' },
    { key: 'ask', label: 'Ask', icon: '💬' },
  ];

  const maxH = compact ? 'max-h-[380px]' : 'max-h-[500px]';

  /* ── Render ──────────────────────────────────────────────────── */
  return (
    <div className="mt-2" onClick={(e) => e.stopPropagation()}>
      {/* Toggle button */}
      <button
        onClick={handleToggle}
        disabled={mainState === 'loading'}
        className="w-full flex items-center justify-center gap-2 py-2.5 rounded-lg border text-xs font-semibold tracking-wide transition-all hover:brightness-125"
        style={{
          borderColor: accent + '40',
          color: accent,
          background: mainState === 'ready' ? accent + '15' : 'transparent',
        }}
      >
        {mainState === 'loading' ? (
          <>
            <Spinner color={accent} /> Generating article about {asteroidName}…
          </>
        ) : mainState === 'ready' ? (
          <>
            <ChevronUp /> Close
          </>
        ) : mainState === 'error' ? (
          <>
            <RetryIcon /> Retry
          </>
        ) : (
          <>
            <RocketIcon /> Explore {asteroidName}
          </>
        )}
      </button>

      {/* Error message */}
      {mainState === 'error' && errorMsg && (
        <p className="mt-1.5 text-[10px] text-red-400/80 text-center">{errorMsg}</p>
      )}

      {/* Main panel */}
      {mainState === 'ready' && (
        <div
          className="mt-2 rounded-xl border overflow-hidden"
          style={{ borderColor: accent + '20', background: 'rgba(0,0,0,0.6)' }}
        >
          {/* Header */}
          <div
            className="px-3 py-2 flex items-center gap-2 border-b"
            style={{ borderColor: accent + '15', background: accent + '08' }}
          >
            <span className="text-sm">🔭</span>
            <span className="text-[11px] font-bold text-white/80 tracking-wide">
              {asteroidName}
            </span>
            <span
              className="ml-auto text-[8px] font-bold tracking-wider uppercase px-1.5 py-0.5 rounded"
              style={{ background: accent + '20', color: accent }}
            >
              AI + NASA
            </span>
          </div>

          {/* Tabs */}
          <div className="flex border-b" style={{ borderColor: accent + '12' }}>
            {tabs.map((t) => (
              <button
                key={t.key}
                onClick={() => (t.key === 'quiz' ? handleQuizTab() : setTab(t.key))}
                className="flex-1 py-2 text-[10px] font-bold tracking-wider uppercase transition-all flex items-center justify-center gap-1"
                style={{
                  color: tab === t.key ? accent : 'rgba(255,255,255,0.35)',
                  borderBottom: tab === t.key ? `2px solid ${accent}` : '2px solid transparent',
                  background: tab === t.key ? accent + '08' : 'transparent',
                }}
              >
                <span>{t.icon}</span> {t.label}
              </button>
            ))}
          </div>

          {/* ─── LEARN TAB ─── */}
          {tab === 'learn' && (
            <div className={`overflow-y-auto ${maxH} px-3 py-3 space-y-3 scrollbar-thin`}>
              {article.map((sec, i) => (
                <div key={i} className="space-y-1">
                  <div className="flex items-center gap-1.5">
                    <span className="text-base">{sec.emoji}</span>
                    <h3
                      className="text-[12px] font-bold tracking-wide"
                      style={{ color: accent }}
                    >
                      {sec.title}
                    </h3>
                  </div>
                  <p className="text-[11px] text-white/75 leading-relaxed pl-6">
                    {sec.content}
                  </p>
                </div>
              ))}

              {/* Prompt to take quiz */}
              <div
                className="mt-2 p-3 rounded-lg border text-center space-y-1.5"
                style={{ borderColor: accent + '20', background: accent + '08' }}
              >
                <p className="text-[11px] text-white/60">
                  Think you got it all? Test your knowledge!
                </p>
                <button
                  onClick={handleQuizTab}
                  className="px-4 py-1.5 rounded-full text-[10px] font-bold tracking-wide transition-all hover:brightness-125"
                  style={{ background: accent, color: '#fff' }}
                >
                  🧠 Take the Quiz
                </button>
              </div>

              {/* Source */}
              <div className="flex items-center gap-1 pt-1">
                <GlobeIcon />
                <a
                  href={nasaInfo?.nasaUrl ?? '#'}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-[9px] text-white/25 hover:text-white/50 transition-colors"
                >
                  Powered by NASA JPL + Google Gemini
                </a>
              </div>
            </div>
          )}

          {/* ─── QUIZ TAB ─── */}
          {tab === 'quiz' && (
            <div className={`overflow-y-auto ${maxH} px-3 py-3 scrollbar-thin`}>
              {quizLoading ? (
                <div className="flex flex-col items-center justify-center gap-3 py-10">
                  <Spinner color={accent} />
                  <span className="text-[11px] text-white/40">
                    Generating your quiz…
                  </span>
                </div>
              ) : quiz.length === 0 ? (
                <div className="text-center py-10">
                  <p className="text-[11px] text-white/40">
                    Could not generate quiz. Try re-opening.
                  </p>
                </div>
              ) : quizDone ? (
                /* ── Score screen ── */
                <div className="flex flex-col items-center justify-center gap-3 py-6">
                  <span className="text-4xl">
                    {score === quiz.length ? '🏆' : score >= quiz.length * 0.6 ? '🌟' : '💪'}
                  </span>
                  <h3 className="text-lg font-bold text-white/90">
                    {score} / {quiz.length}
                  </h3>
                  <p className="text-[11px] text-white/50 text-center max-w-[220px]">
                    {score === quiz.length
                      ? `Perfect score! You're an ${asteroidName} expert! 🎉`
                      : score >= quiz.length * 0.6
                        ? 'Great job! You really paid attention. Keep exploring!'
                        : "Nice try! Go back to the Learn tab and read again — you'll crush it next time!"}
                  </p>
                  <div className="flex gap-2 mt-1">
                    <button
                      onClick={handleRetakeQuiz}
                      className="px-3 py-1.5 rounded-full text-[10px] font-bold border transition-all hover:brightness-125"
                      style={{ borderColor: accent + '40', color: accent }}
                    >
                      🔄 Retake Quiz
                    </button>
                    <button
                      onClick={() => setTab('learn')}
                      className="px-3 py-1.5 rounded-full text-[10px] font-bold transition-all hover:brightness-125"
                      style={{ background: accent + '20', color: accent }}
                    >
                      📖 Review Article
                    </button>
                  </div>
                </div>
              ) : (
                /* ── Question card ── */
                <div className="space-y-3">
                  {/* Progress */}
                  <div className="flex items-center gap-2">
                    <div className="flex-1 h-1 rounded-full bg-white/10 overflow-hidden">
                      <div
                        className="h-full rounded-full transition-all duration-300"
                        style={{
                          width: `${((quizIdx + 1) / quiz.length) * 100}%`,
                          background: accent,
                        }}
                      />
                    </div>
                    <span className="text-[9px] text-white/40 font-mono">
                      {quizIdx + 1}/{quiz.length}
                    </span>
                  </div>

                  {/* Question */}
                  <p className="text-[12px] text-white/90 font-medium leading-relaxed">
                    {quiz[quizIdx].question}
                  </p>

                  {/* Options */}
                  <div className="space-y-1.5">
                    {quiz[quizIdx].options.map((opt, oi) => {
                      const isCorrect = oi === quiz[quizIdx].correct;
                      const isSelected = oi === selected;
                      let bg = 'transparent';
                      let border = 'rgba(255,255,255,0.1)';
                      let textColor = 'rgba(255,255,255,0.7)';

                      if (answered) {
                        if (isCorrect) {
                          bg = 'rgba(34,197,94,0.15)';
                          border = 'rgba(34,197,94,0.5)';
                          textColor = 'rgb(134,239,172)';
                        } else if (isSelected && !isCorrect) {
                          bg = 'rgba(239,68,68,0.15)';
                          border = 'rgba(239,68,68,0.5)';
                          textColor = 'rgb(252,165,165)';
                        }
                      } else if (isSelected) {
                        bg = accent + '15';
                        border = accent;
                        textColor = '#fff';
                      }

                      return (
                        <button
                          key={oi}
                          onClick={() => handleAnswer(oi)}
                          disabled={answered}
                          className="w-full text-left px-3 py-2 rounded-lg border text-[11px] transition-all flex items-center gap-2"
                          style={{
                            background: bg,
                            borderColor: border,
                            color: textColor,
                            cursor: answered ? 'default' : 'pointer',
                          }}
                        >
                          <span
                            className="text-[9px] font-bold w-5 h-5 rounded-full flex items-center justify-center flex-shrink-0"
                            style={{
                              background: answered && isCorrect ? 'rgba(34,197,94,0.3)' : 'rgba(255,255,255,0.08)',
                              color: answered && isCorrect ? 'rgb(134,239,172)' : 'rgba(255,255,255,0.4)',
                            }}
                          >
                            {String.fromCharCode(65 + oi)}
                          </span>
                          {opt}
                          {answered && isCorrect && <span className="ml-auto">✓</span>}
                          {answered && isSelected && !isCorrect && <span className="ml-auto">✗</span>}
                        </button>
                      );
                    })}
                  </div>

                  {/* Explanation */}
                  {answered && (
                    <div
                      className="p-2.5 rounded-lg border text-[10px] leading-relaxed"
                      style={{
                        borderColor:
                          selected === quiz[quizIdx].correct
                            ? 'rgba(34,197,94,0.2)'
                            : 'rgba(239,68,68,0.2)',
                        background:
                          selected === quiz[quizIdx].correct
                            ? 'rgba(34,197,94,0.06)'
                            : 'rgba(239,68,68,0.06)',
                        color: 'rgba(255,255,255,0.6)',
                      }}
                    >
                      <span className="font-bold" style={{ color: selected === quiz[quizIdx].correct ? 'rgb(134,239,172)' : 'rgb(252,165,165)' }}>
                        {selected === quiz[quizIdx].correct ? '🎉 Correct! ' : '❌ Not quite. '}
                      </span>
                      {quiz[quizIdx].explanation}
                    </div>
                  )}

                  {/* Next button */}
                  {answered && (
                    <div className="flex justify-end">
                      <button
                        onClick={handleNext}
                        className="px-4 py-1.5 rounded-full text-[10px] font-bold tracking-wide transition-all hover:brightness-125"
                        style={{ background: accent, color: '#fff' }}
                      >
                        {quizIdx + 1 >= quiz.length ? 'See Results →' : 'Next Question →'}
                      </button>
                    </div>
                  )}
                </div>
              )}
            </div>
          )}

          {/* ─── ASK TAB ─── */}
          {tab === 'ask' && (
            <div className="flex flex-col" style={{ height: compact ? 340 : 460 }}>
              {/* Messages */}
              <div className="flex-1 overflow-y-auto px-3 py-3 space-y-2.5 scrollbar-thin">
                {askMsgs.length === 0 && (
                  <div className="flex flex-col items-center justify-center gap-2 py-8 text-center">
                    <span className="text-2xl">🤖</span>
                    <p className="text-[11px] text-white/40 max-w-[200px]">
                      Ask me anything about {asteroidName}! I have all the NASA data and I'm ready to help.
                    </p>
                  </div>
                )}
                {askMsgs.map((m, i) =>
                  m.role === 'user' ? (
                    <div key={i} className="flex justify-end">
                      <div
                        className="max-w-[85%] px-3 py-2 rounded-2xl rounded-br-sm text-[11px] font-medium text-white"
                        style={{ background: accent + '30' }}
                      >
                        {m.text}
                      </div>
                    </div>
                  ) : (
                    <div key={i} className="flex items-start gap-2">
                      <span className="text-sm flex-shrink-0 mt-0.5">🤖</span>
                      <div
                        className="max-w-[90%] px-3 py-2 rounded-2xl rounded-bl-sm text-[11px] text-white/80 leading-relaxed bg-white/[0.05]"
                        style={{ whiteSpace: 'pre-line' }}
                      >
                        {m.text}
                      </div>
                    </div>
                  ),
                )}
                {askLoading && (
                  <div className="flex items-center gap-2 px-1">
                    <span className="text-sm">🤖</span>
                    <div className="flex gap-1">
                      <span className="w-1.5 h-1.5 rounded-full bg-white/30 animate-bounce" style={{ animationDelay: '0ms' }} />
                      <span className="w-1.5 h-1.5 rounded-full bg-white/30 animate-bounce" style={{ animationDelay: '150ms' }} />
                      <span className="w-1.5 h-1.5 rounded-full bg-white/30 animate-bounce" style={{ animationDelay: '300ms' }} />
                    </div>
                  </div>
                )}
                <div ref={askEndRef} />
              </div>

              {/* Input area */}
              <div className="px-3 py-2.5 border-t flex gap-2" style={{ borderColor: accent + '15' }}>
                <input
                  type="text"
                  value={askInput}
                  onChange={(e) => setAskInput(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' && !e.shiftKey) {
                      e.preventDefault();
                      handleSend();
                    }
                  }}
                  placeholder={`Ask anything about ${asteroidName}…`}
                  disabled={askLoading}
                  className="flex-1 bg-white/[0.06] border border-white/10 rounded-lg px-3 py-1.5 text-[11px] text-white/90 placeholder-white/25 outline-none focus:border-opacity-60 transition-colors"
                  style={{ borderColor: accent + '30' }}
                />
                <button
                  onClick={handleSend}
                  disabled={askLoading || !askInput.trim()}
                  className="px-3 py-1.5 rounded-lg text-[11px] font-bold transition-all hover:brightness-125 disabled:opacity-30"
                  style={{ background: accent, color: '#fff' }}
                >
                  Send
                </button>
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

/* ── Icons ──────────────────────────────────────────────────────── */

function Spinner({ color }: { color: string }) {
  return (
    <svg className="animate-spin" width="14" height="14" viewBox="0 0 24 24" fill="none">
      <circle cx="12" cy="12" r="10" stroke={color} strokeWidth="3" strokeOpacity="0.25" />
      <path d="M12 2a10 10 0 0 1 10 10" stroke={color} strokeWidth="3" strokeLinecap="round" />
    </svg>
  );
}

function RocketIcon() {
  return (
    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <path d="M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09z" />
      <path d="m12 15-3-3a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.35 22.35 0 0 1-4 2z" />
      <path d="M9 12H4s.55-3.03 2-4c1.62-1.08 5 0 5 0" />
      <path d="M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5" />
    </svg>
  );
}

function ChevronUp() {
  return (
    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <polyline points="18 15 12 9 6 15" />
    </svg>
  );
}

function RetryIcon() {
  return (
    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <polyline points="23 4 23 10 17 10" />
      <path d="M20.49 15a9 9 0 1 1-2.12-9.36L23 10" />
    </svg>
  );
}

function GlobeIcon() {
  return (
    <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" className="opacity-30">
      <circle cx="12" cy="12" r="10" />
      <path d="M2 12h20" />
      <path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z" />
    </svg>
  );
}
